steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - builds
  - submit
  - --tag=gcr.io/$_PROJECT_ID/new-beam:latest
  - .
  id: 'build-image'
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args: 
      [ 
          'dataflow'
          , 'flex-template'
          , 'build'
          , '$_TEMPLATE_GCS_LOCATION'
          , '--image'
          , 'gcr.io/$_PROJECT_ID/$_IMAGE_NAME'
          , '--sdk-language'
          , 'PYTHON'
          , '--metadata-file'
          , '$_METADATA_FILE']  
  waitFor: ['build-image']
  id: 'dataflow-template'
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args: 
    [ 
        'dataflow'
        , 'flex-template'
        , 'run'
        , '$_JOB_NAME'
        , '--template-file-gcs-location'
        , '$_TEMPLATE_GCS_LOCATION'
        , '--region=$_REGION'
        ]
  waitFor: ['dataflow-template']
  id: 'build-flex-template-via-cloudsdk'



substitutions:
  _PROJECT_ID: testproject123456789-313307
  _IMAGE_NAME: sitecore:latest
  _TEMPLATE_GCS_LOCATION: gs://demo_bucket123456/template/sitecore_flex_template.json
  _METADATA_FILE: metadata.json 
  _REGION: us-central1
  _JOB_NAME: sitecoredataflowjobtest
