steps:
#- name: gcr.io/$_PROJECT_ID/$_IMAGE_NAME # Useful to debug but somehow this step only works with DirectRunner
#  entrypoint: python
#  args:
#  - /template/main.py
#  - --runner=DirectRunner
#  - --project=$_PROJECT_ID
#  - --region=$_REGION
#  - --job_name=$_JOB_NAME
#  - --temp_location=$_TEMP_LOCATION
#  - --sdk_container_image=gcr.io/$_PROJECT_ID/$_IMAGE_NAME
#  - --disk_size_gb=50
#  - --prebuild_sdk_container_engine=cloud_build
#  id: 'dataflow-template-via-python'
  # Run Flex Template via cloud sdk
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args: 
    [ 
        'dataflow'
        , 'flex-template'
        , 'run'
        , '$_JOB_NAME'
        , '--template-file-gcs-location'
        , '$_TEMPLATE_GCS_LOCATION'
        , '--region=$_REGION'
        ]  
  id: 'build-flex-template-via-cloudsdk'



substitutions:
  #_PROJECT_ID: datascience-projects
  #_IMAGE_NAME: new-beam:latest
  #_TEMP_LOCATION: ''
  _TEMPLATE_GCS_LOCATION: gs://mm_dataflow_bucket/templates/newbeam_flex_template.json
  _JOB_NAME: cloudbuildtesterdr
  _REGION : 'us-central1'
  