package org.ascension.addg.gcp.mdstaff.avro;

import com.typesafe.config.Config;
import com.typesafe.config.ConfigFactory;

public class config {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		String conf = "{\r\n"
				+ "	\"locationConfig\": {\r\n"
				+ "		\"addressConfig\": {\r\n"
				+ "			\r\n"
				+ "			\"singleValueParameters\": {\r\n"
				+ "				\"Country\": \"CountryID_Code\",\r\n"
				+ "				\"City\": \"City\",\r\n"
				+ "				\"AddressLine1\": \"Address\",\r\n"
				+ "				\"AddressLine2\": \"Address2\",\r\n"
				+ "				\"StateProvince\": \"State\",\r\n"
				+ "				\"SubAdministrativeArea\": \"CountyID_Code\",\r\n"
				+ "				\"PublishToExternalDirectoryFlag\": \"PubAddrExtDir\",\r\n"
				+ "				\"PublishToExternalDirectoryPrimaryFlag\": \"PubAddrExtPrim\",\r\n"
				+ "				\"AddressInUse\": \"InUse\",\r\n"
				+ "			\r\n"
				+ "			}\r\n"
				+ "			\r\n"
				+ "			\"crosswalks\": {\r\n"
				+ "				\"key\": \"AddressID\",\r\n"
				+ "			}\r\n"
				+ "			\r\n"
				+ "			\"Zip\": {\r\n"
				+ "				\"PostalCode\": \"Zip\",\r\n"
				+ "				\"Zip5\": \"NoRecord\",\r\n"
				+ "				\"Zip4\": \"NoRecord\",\r\n"
				+ "			}\r\n"
				+ "			\r\n"
				+ "			\"SystemIdentifier\": {\r\n"
				+ "				\"ProviderID\": \"ProviderID\",\r\n"
				+ "				\"AddressID\": \"AddressID\",\r\n"
				+ "			}\r\n"
				+ "		}\r\n"
				+ "		\r\n"
				+ "		\"siteConfig\": {\r\n"
				+ "			\"singleValueParameters\": {\r\n"
				+ "				\"AddressLine1\": \"Address1\",\r\n"
				+ "				\"AddressLine2\": \"Address2\",\r\n"
				+ "				\"City\": \"City\",\r\n"
				+ "				\"SubAdministrativeArea\": \"CountyID_Code\",\r\n"
				+ "				\"StateProvince\": \"StateProvince\",\r\n"
				+ "				\"Country\": \"NoRecord\",\r\n"
				+ "				\"PublishToExternalDirectoryFlag\": \"NoRecord\",\r\n"
				+ "				\"PublishToExternalDirectoryPrimaryFlag\": \"NoRecord\",\r\n"
				+ "				\"AddressInUse\": \"InUse\",\r\n"
				+ "			}\r\n"
				+ "			\r\n"
				+ "			\"crosswalks\": {\r\n"
				+ "				\"key\": \"SiteID\",\r\n"
				+ "			}\r\n"
				+ "			\r\n"
				+ "			\"Zip\": {\r\n"
				+ "				\"PostalCode\": \"PostalCode\",\r\n"
				+ "				\"Zip5\": \"NoRecord\",\r\n"
				+ "				\"Zip4\": \"NoRecord\",\r\n"
				+ "			}\r\n"
				+ "			\r\n"
				+ "			\"SystemIdentifier\": {\r\n"
				+ "				\"SiteID\": \"SiteID\",\r\n"
				+ "				\"EntityID\": \"EntityID\",\r\n"
				+ "			}\r\n"
				+ "		}\r\n"
				+ "	\r\n"
				+ "	}\r\n"
				+ "	\r\n"
				+ "	\"hcoConfig\": {\r\n"
				+ "		\"entityConfig\": {\r\n"
				+ "			\"singleValueParameters\": {\r\n"
				+ "				\"OrganizationName\": \"Name\",\r\n"
				+ "				\"OrganizationTypeCode\": \"Entity\",\r\n"
				+ "				\"OrganizationCode\": \"NoRecord\",\r\n"
				+ "				\"Status\": \"NoRecord\",\r\n"
				+ "				\"EntityInUseFlag\": \"InUse\",\r\n"
				+ "				\"SiteInUseFlag\": \"NoRecord\",\r\n"
				+ "				\"FacilityArchivedFlag\": \"NoRecord\",\r\n"
				+ "				\"DoingBusinessAs\": \"NoRecord\",\r\n"
				+ "				\"PatientCenteredMedicalHomeFlag\": \"NoRecord\",\r\n"
				+ "			\r\n"
				+ "			}\r\n"
				+ "			\r\n"
				+ "			\"crosswalks\": {\r\n"
				+ "				\"key\": \"EntityID\",\r\n"
				+ "			}\r\n"
				+ "			\r\n"
				+ "			\"managedIdentifier\": {\r\n"
				+ "				\"nationalIdentifier\": {\r\n"
				+ "					\"ManagedIdentifierType\": \"National Provider Identifier\",\r\n"
				+ "					\"ManagedIdentifierValue\": \"NPI\",\r\n"
				+ "					\"IssuingAuthority\": \"NoRecord\",\r\n"
				+ "					\"State\": \"NoRecord\",\r\n"
				+ "					\"InitialIssueDate\": \"NoRecord\",\r\n"
				+ "					\"EffectiveDate\": \"NoRecord\",\r\n"
				+ "					\"RenewalDate\": \"NoRecord\",\r\n"
				+ "					\"ExpirationDate\": \"NoRecord\",\r\n"
				+ "				}\r\n"
				+ "				\r\n"
				+ "				\"medicareIdentifier\": {\r\n"
				+ "					\"ManagedIdentifierType\": \"Provider Transaction Access Number\",\r\n"
				+ "					\"ManagedIdentifierValue\": \"MedicareNumber\",\r\n"
				+ "					\"IssuingAuthority\": \"NoRecord\",\r\n"
				+ "					\"State\": \"NoRecord\",\r\n"
				+ "					\"InitialIssueDate\": \"NoRecord\",\r\n"
				+ "					\"EffectiveDate\": \"NoRecord\",\r\n"
				+ "					\"RenewalDate\": \"NoRecord\",\r\n"
				+ "					\"ExpirationDate\": \"NoRecord\",\r\n"
				+ "				}\r\n"
				+ "				\r\n"
				+ "				\"medicaidIdentifier\": {\r\n"
				+ "					\"ManagedIdentifierType\": \"Medicaid Number\",\r\n"
				+ "					\"ManagedIdentifierValue\": \"MedicaidNumber\",\r\n"
				+ "					\"IssuingAuthority\": \"NoRecord\",\r\n"
				+ "					\"State\": \"NoRecord\",\r\n"
				+ "					\"InitialIssueDate\": \"NoRecord\",\r\n"
				+ "					\"EffectiveDate\": \"NoRecord\",\r\n"
				+ "					\"RenewalDate\": \"NoRecord\",\r\n"
				+ "					\"ExpirationDate\": \"NoRecord\",\r\n"
				+ "				}\r\n"
				+ "				\r\n"
				+ "				\"taxPayerIdentifier\": {\r\n"
				+ "					\"ManagedIdentifierType\": \"Taxpayer Identification Number\",\r\n"
				+ "					\"ManagedIdentifierValue\": \"TaxIDNumber\",\r\n"
				+ "					\"IssuingAuthority\": \"NoRecord\",\r\n"
				+ "					\"State\": \"NoRecord\",\r\n"
				+ "					\"InitialIssueDate\": \"NoRecord\",\r\n"
				+ "					\"EffectiveDate\": \"NoRecord\",\r\n"
				+ "					\"RenewalDate\": \"NoRecord\",\r\n"
				+ "					\"ExpirationDate\": \"NoRecord\",\r\n"
				+ "				}\r\n"
				+ "				\r\n"
				+ "			}\r\n"
				+ "			\r\n"
				+ "			\"SystemIdentifier\": {\r\n"
				+ "				\"ParentEntityID\": \"ParentEntityID\",\r\n"
				+ "				\"EntityID\": \"EntityID\",\r\n"
				+ "			}\r\n"
				+ "			\r\n"
				+ "			\"Email\": {\r\n"
				+ "				\"EmailType\": \"NoRecord\",\r\n"
				+ "				\"Email\": \"NoRecord\",\r\n"
				+ "			}\r\n"
				+ "		}\r\n"
				+ "		\r\n"
				+ "		\"siteConfig\": {\r\n"
				+ "			\"singleValueParameters\": {\r\n"
				+ "				\"OrganizationName\": \"Name\",\r\n"
				+ "				\"OrganizationTypeCode\": \"SiteType_Code\",\r\n"
				+ "				\"OrganizationCode\": \"NoRecord\",\r\n"
				+ "				\"Status\": \"NoRecord\",\r\n"
				+ "				\"EntityInUseFlag\": \"NoRecord\",\r\n"
				+ "				\"SiteInUseFlag\": \"InUse\",\r\n"
				+ "				\"FacilityArchivedFlag\": \"NoRecord\",\r\n"
				+ "				\"DoingBusinessAs\": \"NoRecord\",\r\n"
				+ "				\"PatientCenteredMedicalHomeFlag\": \"PCMHID_Code\",\r\n"
				+ "			\r\n"
				+ "			}\r\n"
				+ "			\r\n"
				+ "			\"crosswalks\": {\r\n"
				+ "				\"key\": \"SiteID\",\r\n"
				+ "			}\r\n"
				+ "			\r\n"
				+ "			\"managedIdentifier\": {\r\n"
				+ "				\"nationalIdentifier\": {\r\n"
				+ "					\"ManagedIdentifierType\": \"National Provider Identifier\",\r\n"
				+ "					\"ManagedIdentifierValue\": \"NPI\",\r\n"
				+ "					\"IssuingAuthority\": \"NoRecord\",\r\n"
				+ "					\"State\": \"NoRecord\",\r\n"
				+ "					\"InitialIssueDate\": \"NoRecord\",\r\n"
				+ "					\"EffectiveDate\": \"NoRecord\",\r\n"
				+ "					\"RenewalDate\": \"NoRecord\",\r\n"
				+ "					\"ExpirationDate\": \"NoRecord\",\r\n"
				+ "				},\r\n"
				+ "				\r\n"
				+ "				\"medicareIdentifier\": {\r\n"
				+ "					\"ManagedIdentifierType\": \"Provider Transaction Access Number\",\r\n"
				+ "					\"ManagedIdentifierValue\": \"MedicareNumber\",\r\n"
				+ "					\"IssuingAuthority\": \"NoRecord\",\r\n"
				+ "					\"State\": \"NoRecord\",\r\n"
				+ "					\"InitialIssueDate\": \"NoRecord\",\r\n"
				+ "					\"EffectiveDate\": \"NoRecord\",\r\n"
				+ "					\"RenewalDate\": \"NoRecord\",\r\n"
				+ "					\"ExpirationDate\": \"NoRecord\",\r\n"
				+ "				},\r\n"
				+ "				\r\n"
				+ "				\"medicaidIdentifier\": {\r\n"
				+ "					\"ManagedIdentifierType\": \"Medicaid Number\",\r\n"
				+ "					\"ManagedIdentifierValue\": \"MedicaidNumber\",\r\n"
				+ "					\"IssuingAuthority\": \"NoRecord\",\r\n"
				+ "					\"State\": \"NoRecord\",\r\n"
				+ "					\"InitialIssueDate\": \"NoRecord\",\r\n"
				+ "					\"EffectiveDate\": \"NoRecord\",\r\n"
				+ "					\"RenewalDate\": \"NoRecord\",\r\n"
				+ "					\"ExpirationDate\": \"NoRecord\",\r\n"
				+ "				},\r\n"
				+ "				\r\n"
				+ "				\"taxPayerIdentifier\": {\r\n"
				+ "					\"ManagedIdentifierType\": \"Taxpayer Identification Number\",\r\n"
				+ "					\"ManagedIdentifierValue\": \"TaxIDNumber\",\r\n"
				+ "					\"IssuingAuthority\": \"NoRecord\",\r\n"
				+ "					\"State\": \"NoRecord\",\r\n"
				+ "					\"InitialIssueDate\": \"NoRecord\",\r\n"
				+ "					\"EffectiveDate\": \"NoRecord\",\r\n"
				+ "					\"RenewalDate\": \"NoRecord\",\r\n"
				+ "					\"ExpirationDate\": \"NoRecord\",\r\n"
				+ "				},\r\n"
				+ "				\r\n"
				+ "			}\r\n"
				+ "			\r\n"
				+ "			\"SystemIdentifier\": {\r\n"
				+ "				\"SiteID\": \"SiteID\",\r\n"
				+ "				\"EntityID\": \"EntityID\",\r\n"
				+ "			}\r\n"
				+ "			\r\n"
				+ "			\"Email\": {\r\n"
				+ "				\"EmailType\": \"NoRecord\",\r\n"
				+ "				\"Email\": \"NoRecord\",\r\n"
				+ "			}\r\n"
				+ "		}\r\n"
				+ "		\r\n"
				+ "		\"facilityConfig\": {\r\n"
				+ "			\"singleValueParameters\": {\r\n"
				+ "				\"OrganizationName\": \"Comments\",\r\n"
				+ "				\"OrganizationTypeCode\": \"Facility\",\r\n"
				+ "				\"OrganizationCode\": \"Code\",\r\n"
				+ "				\"Status\": \"NoRecord\",\r\n"
				+ "				\"EntityInUseFlag\": \"NoRecord\",\r\n"
				+ "				\"SiteInUseFlag\": \"NoRecord\",\r\n"
				+ "				\"FacilityArchivedFlag\": \"Archived\",\r\n"
				+ "				\"DoingBusinessAs\": \"NoRecord\",\r\n"
				+ "				\"PatientCenteredMedicalHomeFlag\": \"NoRecord\",\r\n"
				+ "			\r\n"
				+ "			}\r\n"
				+ "			\r\n"
				+ "			\"managedIdentifier\": {\r\n"
				+ "				\"identifier\": {\r\n"
				+ "					\"ManagedIdentifierType\": \"NoRecord\",\r\n"
				+ "					\"ManagedIdentifierValue\": \"NoRecord\",\r\n"
				+ "					\"IssuingAuthority\": \"NoRecord\",\r\n"
				+ "					\"State\": \"NoRecord\",\r\n"
				+ "					\"InitialIssueDate\": \"NoRecord\",\r\n"
				+ "					\"EffectiveDate\": \"NoRecord\",\r\n"
				+ "					\"RenewalDate\": \"NoRecord\",\r\n"
				+ "					\"ExpirationDate\": \"NoRecord\",\r\n"
				+ "					}\r\n"
				+ "			}\r\n"
				+ "			\r\n"
				+ "			\"crosswalks\": {\r\n"
				+ "				\"key\": \"FacilityID\",\r\n"
				+ "			}\r\n"
				+ "			\r\n"
				+ "			\"SystemIdentifier\": {\r\n"
				+ "				\"FacilityID\": \"FacilityID\",\r\n"
				+ "			}\r\n"
				+ "			\r\n"
				+ "			\"Email\": {\r\n"
				+ "				\"EmailType\": \"NoRecord\",\r\n"
				+ "				\"Email\": \"NoRecord\",\r\n"
				+ "			}\r\n"
				+ "		\r\n"
				+ "		}\r\n"
				+ "	\r\n"
				+ "	\r\n"
				+ "	}\r\n"
				+ "	\r\n"
				+ "	\"clinicalExpertiseConfig\": {\r\n"
				+ "		\"entityName\": \"ClinicalExpertise\",\r\n"
				+ "		\"codeValueColumns\": [ \"ClinicalExpertise1_Code\", \"ClinicalExpertise2_Code\", \"ClinicalExpertise3_Code\", \"ClinicalExpertise4_Code\" ],\r\n"
				+ "		\r\n"
				+ "		\"crosswalks\": {\r\n"
				+ "				\"key\": \"ClinicalExpertise\",\r\n"
				+ "		}\r\n"
				+ "	}\r\n"
				+ "	\r\n"
				+ "	\"specialtyExpertiseConfig\": {\r\n"
				+ "		\"entityName\": \"Specialty\",\r\n"
				+ "		\"codeValueColumns\": [ \"Specialty1_Code\", \"Specialty2_Code\", \"Specialty3_Code\", \"Specialty4_Code\" ],\r\n"
				+ "		\r\n"
				+ "		\"crosswalks\": {\r\n"
				+ "				\"key\": \"Specialty\",\r\n"
				+ "		}\r\n"
				+ "	}\r\n"
				+ "	\r\n"
				+ "	\"ministryConfig\": {\r\n"
				+ "		\"entityName\": \"Ministry\",\r\n"
				+ "		\"codeValueColumns\": [ \"MinistryAssociation_Code\" ],\r\n"
				+ "		\r\n"
				+ "		\"crosswalks\": {\r\n"
				+ "				\"key\": \"Ministry\",\r\n"
				+ "		}\r\n"
				+ "	}\r\n"
				+ "	\r\n"
				+ "	\"indConfig\":  {\r\n"
				+ "		\"reference\": [ \"ProviderID\", \"ReferenceID\", \"DegreeEarnedID_Code\", \"Subject\", \"InUse\", \"StartDate\", \"EndDate\", \"ReferenceSourceID\", \"LastUpdated\" ],\r\n"
				+ "		\"referenceSource\": [ \"ReferenceSourceID\", \"Code\", \"Name\", \"ReferenceType\", \"Archived\", \"LastUpdated\" ],\r\n"
				+ "		\"educationParams\": [ \"Name\", \"ReferenceType\", \"Archived\", \"InUse\", \"Subject\", \"DegreeEarnedID_Code\", \"StartDate\", \"EndDate\" ],\r\n"
				+ "		\r\n"
				+ "		\"eduConf\": {\r\n"
				+ "			\"educationStructConfig\": {\r\n"
				+ "				\"EducationInstitution\": \"Name\",\r\n"
				+ "				\"EducationTypeCode\": \"ReferenceType\",\r\n"
				+ "				\"ReferenceSourceArchivedFlag\": \"Archived\",\r\n"
				+ "				\"ReferenceInUseFlag\": \"InUse\",\r\n"
				+ "				\"SubjectOfStudy\": \"Subject\",\r\n"
				+ "				\"AcademicDegreeCode\": \"DegreeEarnedID_Code\",\r\n"
				+ "				\"AcademicDegreeStartDate\": \"StartDate\",\r\n"
				+ "				\"AcademicDegreeEndDate\": \"EndDate\"\r\n"
				+ "			}\r\n"
				+ "		}\r\n"
				+ "		\r\n"
				+ "		\"aliasConfig\": {\r\n"
				+ "			\"alias_codes\": [ \"OTHER\", \"PreviousName\" ],\r\n"
				+ "			\"alias_params\": [ \"ProviderID\", \"AliasID\", \"AliasTypeID_Code\", \"GivenName\", \"FamilyName\" ],\r\n"
				+ "			\"alias_struct_params\": {\r\n"
				+ "				\"AliasNameTypeCode\": \"AliasTypeID_Code\",\r\n"
				+ "				\"AliasGivenName\": \"GivenName\",\r\n"
				+ "				\"AliasFamilyName\": \"FamilyName\",\r\n"
				+ "				\"AliasMiddleName\": \"NoRecord\",\r\n"
				+ "			}\r\n"
				+ "			\r\n"
				+ "			\"check_param\": \"AliasTypeID_Code\",\r\n"
				+ "		}\r\n"
				+ "		\r\n"
				+ "		\"cred\": {\r\n"
				+ "			\"credParams\": [ \"CredentialID\", \"ProviderID\", \"Issued\", \"Renewed\", \"Expired\", \"LicenseNumber\",\r\n"
				+ "							\"LicenseTypeID_Code\", \"LicenseSubType_Code\", \"LicensureBoardID_Code\", \"State\",\r\n"
				+ "							\"StateProfessionID\", \"Status\", \"InUse\", \"LastUpdated\" ],\r\n"
				+ "			\"checkCol\": \"LicenseTypeID_Code\",\r\n"
				+ "			\"joinKey\": \"ProviderID\",\r\n"
				+ "			\r\n"
				+ "			\"managedIdentifierConf\": {\r\n"
				+ "				\"managedIdentifierValues\": {\r\n"
				+ "					\"ManagedIdentifierValue\": \"LicenseNumber\",\r\n"
				+ "					\"StateProfessionalLicenseTypeCode\": \"LicenseSubType_Code\",\r\n"
				+ "					\"IssuingAuthority\": \"LicensureBoardID_Code\",\r\n"
				+ "					\"State\": \"State\",\r\n"
				+ "					\"InitialIssueDate\": \"Issued\",\r\n"
				+ "					\"EffectiveDate\": \"NoRecord\",\r\n"
				+ "					\"RenewalDate\": \"Renewed\",\r\n"
				+ "					\"ExpirationDate\": \"Expired\",\r\n"
				+ "					\"CredentialInUseFlag\": \"InUse\",\r\n"
				+ "					\"Profession\": \"StateProfessionID\"\r\n"
				+ "				\r\n"
				+ "				},\r\n"
				+ "				\r\n"
				+ "				\"remove\": [ \"LicenseNumber\", \"LicenseSubType_Code\", \"LicensureBoardID_Code\", \"State\", \"Issued\", \"Renewed\",\r\n"
				+ "							\"Expired\", \"InUse\", \"LicenseTypeID_Code\", \"CredentialID\", \"StateProfessionID\", \"Status\" ],\r\n"
				+ "			}\r\n"
				+ "		}\r\n"
				+ "		\r\n"
				+ "		\"indManagedIdentifierConf\": {\r\n"
				+ "			\r\n"
				+ "			\"cred\": [ \"spl\", \"dea\", \"cds\" ],\r\n"
				+ "			\"commonCredVals\": [ \"ManagedIdentifierValue\", \"StateProfessionalLicenseTypeCode\", \"IssuingAuthority\", \"Profession\",\r\n"
				+ "								\"State\", \"InitialIssueDate\", \"EffectiveDate\", \"RenewalDate\", \"ExpirationDate\", \"CredentialInUseFlag\" ],\r\n"
				+ "								\r\n"
				+ "			\"credVals\": [ \"ManagedIdentifierType\", \"ManagedIdentifierValue\", \"StateProfessionalLicenseTypeCode\", \"IssuingAuthority\", 	\"Profession\", \"State\", \"InitialIssueDate\", \"EffectiveDate\", \"RenewalDate\", \"ExpirationDate\", \"CredentialInUseFlag\" ],\r\n"
				+ "			\"credValIdentifiers\": {\r\n"
				+ "				\"spl\": {\r\n"
				+ "					\"ManagedIdentifierType\": \"State Professional License\",\r\n"
				+ "				},\r\n"
				+ "				\"dea\": {\r\n"
				+ "					\"ManagedIdentifierType\": \"Drug Enforcement Agency Number\",\r\n"
				+ "				},\r\n"
				+ "				\"cds\": {\r\n"
				+ "					\"ManagedIdentifierType\": \"Controlled Dangerous Substance License Number\",\r\n"
				+ "				},\r\n"
				+ "				\r\n"
				+ "			}\r\n"
				+ "			\"simpleParams\": [ \"NPI\", \"MedicareNumber\", \"MedicaidNumber\", \"TaxID\" ],\r\n"
				+ "			\"simpleParamsConfig\": {\r\n"
				+ "				\"NPI\": \"National Provider Identifier\",\r\n"
				+ "				\"MedicareNumber\": \"Provider Transaction Access Number\",\r\n"
				+ "				\"MedicaidNumber\": \"Medicaid Number\",\r\n"
				+ "				\"TaxID\": \"Taxpayer Identification Number\",\r\n"
				+ "			},\r\n"
				+ "			\r\n"
				+ "			\"emptyVals\": [ \"StateProfessionalLicenseTypeCode\", \"IssuingAuthority\", \"Profession\", \"State\", \"InitialIssueDate\", \r\n"
				+ "							\"EffectiveDate\", \"RenewalDate\", \"ExpirationDate\", \"CredentialInUseFlag\" ],\r\n"
				+ "			\"singlaValIdentifiers\": {\r\n"
				+ "				\"NPI\": {\r\n"
				+ "					\"ManagedIdentifierType\": \"National Provider Identifier\",\r\n"
				+ "					\"ManagedIdentifierValue\": \"NPI\",\r\n"
				+ "					\"StateProfessionalLicenseTypeCode\": \"NoRecord\",\r\n"
				+ "					\"IssuingAuthority\": \"NoRecord\",\r\n"
				+ "					\"Profession\": \"NoRecord\",\r\n"
				+ "					\"State\": \"NoRecord\",\r\n"
				+ "					\"InitialIssueDate\": \"NoRecord\",\r\n"
				+ "					\"EffectiveDate\": \"NoRecord\",\r\n"
				+ "					\"RenewalDate\": \"NoRecord\",\r\n"
				+ "					\"ExpirationDate\": \"NoRecord\",\r\n"
				+ "					\"CredentialInUseFlag\": \"NoRecord\",\r\n"
				+ "				},\r\n"
				+ "				\"MedicareNumber\": {\r\n"
				+ "					\"ManagedIdentifierType\": \"Provider Transaction Access Number\",\r\n"
				+ "					\"ManagedIdentifierValue\": \"MedicareNumber\",\r\n"
				+ "					\"StateProfessionalLicenseTypeCode\": \"NoRecord\",\r\n"
				+ "					\"IssuingAuthority\": \"NoRecord\",\r\n"
				+ "					\"Profession\": \"NoRecord\",\r\n"
				+ "					\"State\": \"NoRecord\",\r\n"
				+ "					\"InitialIssueDate\": \"NoRecord\",\r\n"
				+ "					\"EffectiveDate\": \"NoRecord\",\r\n"
				+ "					\"RenewalDate\": \"NoRecord\",\r\n"
				+ "					\"ExpirationDate\": \"NoRecord\",\r\n"
				+ "					\"CredentialInUseFlag\": \"NoRecord\",\r\n"
				+ "				},\r\n"
				+ "				\"Medicaid Number\": {\r\n"
				+ "					\"ManagedIdentifierType\": \"Medicaid Number\",\r\n"
				+ "					\"ManagedIdentifierValue\": \"MedicareNumber\",\r\n"
				+ "					\"StateProfessionalLicenseTypeCode\": \"NoRecord\",\r\n"
				+ "					\"IssuingAuthority\": \"NoRecord\",\r\n"
				+ "					\"Profession\": \"NoRecord\",\r\n"
				+ "					\"State\": \"NoRecord\",\r\n"
				+ "					\"InitialIssueDate\": \"NoRecord\",\r\n"
				+ "					\"EffectiveDate\": \"NoRecord\",\r\n"
				+ "					\"RenewalDate\": \"NoRecord\",\r\n"
				+ "					\"ExpirationDate\": \"NoRecord\",\r\n"
				+ "					\"CredentialInUseFlag\": \"NoRecord\",\r\n"
				+ "				},\r\n"
				+ "				\"TaxID\": {\r\n"
				+ "					\"ManagedIdentifierType\": \"Taxpayer Identification Number\",\r\n"
				+ "					\"ManagedIdentifierValue\": \"TaxID\",\r\n"
				+ "					\"StateProfessionalLicenseTypeCode\": \"NoRecord\",\r\n"
				+ "					\"IssuingAuthority\": \"NoRecord\",\r\n"
				+ "					\"Profession\": \"NoRecord\",\r\n"
				+ "					\"State\": \"NoRecord\",\r\n"
				+ "					\"InitialIssueDate\": \"NoRecord\",\r\n"
				+ "					\"EffectiveDate\": \"NoRecord\",\r\n"
				+ "					\"RenewalDate\": \"NoRecord\",\r\n"
				+ "					\"ExpirationDate\": \"NoRecord\",\r\n"
				+ "					\"CredentialInUseFlag\": \"NoRecord\",\r\n"
				+ "				},\r\n"
				+ "			}\r\n"
				+ "		\r\n"
				+ "		}\r\n"
				+ "		\r\n"
				+ "		\"boardConfig\": {\r\n"
				+ "			\"ifnullparam\": {\r\n"
				+ "				\"checkExpr\": \"SpecialtyID_Code\",\r\n"
				+ "				\"backupVal\": \"SpecializationID_Code\",\r\n"
				+ "				\"colName\": \"BoardCertificationSpecialtyCode\",\r\n"
				+ "			},\r\n"
				+ "			\r\n"
				+ "			\"singleValueParameters\": {\r\n"
				+ "				\"BoardCertificationCode\": \"SpecialtyBoardID_Code\",\r\n"
				+ "				\"BoardCertificationStatusCode\": \"CertificationStatusID_Code\",\r\n"
				+ "				\"BoardCertificationNumber\": \"CertificationNumber\",\r\n"
				+ "				\"BoardCertificationLifetimeStatus\": \"Lifetime\",\r\n"
				+ "				\"BoardCertificationInUseFlag\": \"InUse\",\r\n"
				+ "				\"BoardCertificationInitialDate\": \"InitialCertificationDate\",\r\n"
				+ "				\"BoardCertificationExpirationDate\": \"ExpirationDate\",\r\n"
				+ "				\"BoardCertificationExamDate\": \"ExamDate\"\r\n"
				+ "			}\r\n"
				+ "		}\r\n"
				+ "		\r\n"
				+ "		\"demoConfig\": {\r\n"
				+ "			\"singleValueParameters\": {\r\n"
				+ "        		\"GivenName\": \"FirstName\",\r\n"
				+ "        		\"FamilyName\": \"LastName\",\r\n"
				+ "        		\"MiddleName\": \"MiddleName\",\r\n"
				+ "        		\"FullName\": \"NoRecord\",\r\n"
				+ "        		\"Status\": \"NoRecord\",\r\n"
				+ "        		\"DOB\": \"BirthDate\",\r\n"
				+ "        		\"AdministrativeGenderCode\": \"GenderID_Code\",\r\n"
				+ "        		\"SSN\": \"SSN\",\r\n"
				+ "        		\"NameSuffixCode\": \"SuffixID_Code\",\r\n"
				+ "        		\"FieldofLicensureCode\": \"FieldOfLicensureID_Code\",\r\n"
				+ "        		\"PreferredName\": \"PreferredName\",\r\n"
				+ "        		\"NamePrefixCode\": \"PrefixID_Code\",\r\n"
				+ "        		\"RaceCode\": \"RaceID_Code\",\r\n"
				+ "        		\"EthnicityCode\": \"EthnicityID_Code\",\r\n"
				+ "        		\"DomesticPartnerName\": \"SpouseName\",\r\n"
				+ "        		\"MaritalStatusCode\": \"MaritalStatusID_Code\",\r\n"
				+ "        		\"DeceasedFlag\": \"Deceased\",\r\n"
				+ "        		\"DeathDate\": \"DeceasedDate\",\r\n"
				+ "        		\"ProviderID\": \"ProviderID\",\r\n"
				+ "        		\"NPI\": \"NPI\",\r\n"
				+ "        		\"MedicareNumber\": \"MedicareNumber\",\r\n"
				+ "        		\"MedicaidNumber\": \"MedicaidNumber\",\r\n"
				+ "        		\"TaxID\": \"TaxID\",\r\n"
				+ "				\r\n"
				+ "        	}\r\n"
				+ "			\r\n"
				+ "			\"crosswalks\": {\r\n"
				+ "				\"key\": \"ProviderID\",\r\n"
				+ "			}\r\n"
				+ "			\r\n"
				+ "			\"SystemIdentifier\": {\r\n"
				+ "				\"key\": \"ProviderID\",\r\n"
				+ "				\"ProviderID\": \"ProviderID\",\r\n"
				+ "			}\r\n"
				+ "			\r\n"
				+ "			\r\n"
				+ "			\"Credential\": {\r\n"
				+ "				\"CredentialCode\": [ \"DegreeID_1_Code\", \"DegreeID_2_Code\", \"DegreeID_3_Code\" ],\r\n"
				+ "				\"Rank\": \"CredentialRank\",\r\n"
				+ "				\"CodeValue\": \"CredentialCode\",\r\n"
				+ "				\r\n"
				+ "			}\r\n"
				+ "			\r\n"
				+ "			\"LanguageSpoken\": {\r\n"
				+ "				\"LanguageSpokenCode\": [ \"LanguageID_1_Code\", \"LanguageID_2_Code\", \"LanguageID_3_Code\", \"LanguageID_4_Code\", \"LanguageID_5_Code\" ],\r\n"
				+ "				\"Rank\": \"LanguageSpokenRank\",\r\n"
				+ "				\"CodeValue\": \"LanguageSpokenCode\",\r\n"
				+ "			}\r\n"
				+ "			\r\n"
				+ "			\r\n"
				+ "			\"phone\": {\r\n"
				+ "				\"Phone\": {\r\n"
				+ "					\"PhoneType\": \"Mobile\",\r\n"
				+ "					\"Number\": \"CellPhone\",\r\n"
				+ "					\"Extension\": \"NoRecord\",\r\n"
				+ "					\"Rank\": \"NoRecord\",\r\n"
				+ "				}\r\n"
				+ "				\r\n"
				+ "				\"Pager\": {\r\n"
				+ "					\"PhoneType\": \"Pager\",\r\n"
				+ "					\"Number\": \"Pager\",\r\n"
				+ "					\"Extension\": \"NoRecord\",\r\n"
				+ "					\"Rank\": \"NoRecord\",\r\n"
				+ "				}\r\n"
				+ "			\r\n"
				+ "			}\r\n"
				+ "			\r\n"
				+ "			\r\n"
				+ "		\r\n"
				+ "		}\r\n"
				+ "	\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "";
		
		Config cnf = ConfigFactory.parseString(conf).resolve();
		
		cnf.entrySet().forEach((k)->{
			System.out.println(k);
		});
	}

}
